// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVaK_LH05K3qYj9dA5L8ivprI2qltQhoo',
    appId: '1:327742061526:web:771f3e2e573d56eef48277',
    messagingSenderId: '327742061526',
    projectId: 'studibudi-217c0',
    authDomain: 'studibudi-217c0.firebaseapp.com',
    storageBucket: 'studibudi-217c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBN5NUkYB6Xhnu-VDiKaXKEtsAaKW-DU',
    appId: '1:327742061526:android:baef0b44f63df8a2f48277',
    messagingSenderId: '327742061526',
    projectId: 'studibudi-217c0',
    storageBucket: 'studibudi-217c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12pAAJlhPG-gD1HL8R4TTzKqKH0KXBUI',
    appId: '1:327742061526:ios:0ef3dbb78e1c1a67f48277',
    messagingSenderId: '327742061526',
    projectId: 'studibudi-217c0',
    storageBucket: 'studibudi-217c0.appspot.com',
    iosBundleId: 'com.example.shushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12pAAJlhPG-gD1HL8R4TTzKqKH0KXBUI',
    appId: '1:327742061526:ios:0d9c41b5e76489c2f48277',
    messagingSenderId: '327742061526',
    projectId: 'studibudi-217c0',
    storageBucket: 'studibudi-217c0.appspot.com',
    iosBundleId: 'com.example.shushApp.RunnerTests',
  );
}
